name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup docker-compose 2
      run: docker-compose up
    - name: run test
      run : docker exec backend sh -c "flake && pytest ."
    
      
