name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup docker-compose
      run: docker-compose up -d
    - name: install flake8
      run: docker-compose exec -T backend sh -c "pip install flake8"
    - name: Run Test
      run: docker-compose exec -T backend sh -c "flake8 && pytest ."
